// Book data array with complete information
const books = [
  {
    id: 1,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "Business",
    price: 14.99,
    originalPrice: 19.99,
    rating: 4.5,
    reviews: 1234,
    description: "Timeless lessons on wealth, greed, and happiness. Doing well with money isn't necessarily about what you know. It's about how you behave. And behavior is hard to teach, even to really smart people. This book will help you understand the strange ways people think about money and teach you how to make better sense of one of life's most important topics.",
    coverImage: "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=400&h=600&fit=crop",
    pages: 256,
    publishedDate: "2020-09-08",
    format: "eBook",
    fileSize: "2.5 MB",
    priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB" // Replace with your Stripe Price ID
  }
  // {
  //   id: 2,
  //   title: "Atomic Habits",
  //   author: "James Clear",
  //   category: "Self-Help",
  //   price: 12.99,
  //   originalPrice: 16.99,
  //   rating: 4.8,
  //   reviews: 5678,
  //   description: "An Easy & Proven Way to Build Good Habits & Break Bad Ones. No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
  //   coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
  //   pages: 320,
  //   publishedDate: "2018-10-16",
  //   format: "eBook",
  //   fileSize: "3.1 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 3,
  //   title: "The Midnight Library",
  //   author: "Matt Haig",
  //   category: "Fiction",
  //   price: 11.99,
  //   originalPrice: 15.99,
  //   rating: 4.6,
  //   reviews: 3456,
  //   description: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices. Would you have done anything different, if you had the chance to undo your regrets?",
  //   coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop",
  //   pages: 288,
  //   publishedDate: "2020-08-13",
  //   format: "eBook",
  //   fileSize: "2.8 MB",
  //   priceId: "price_1QQk5bCLF4yRKjWwdBwJEfJO"
  // },
  // {
  //   id: 4,
  //   title: "Dune",
  //   author: "Frank Herbert",
  //   category: "Sci-Fi",
  //   price: 13.99,
  //   originalPrice: 18.99,
  //   rating: 4.7,
  //   reviews: 8901,
  //   description: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the 'spice' melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for.",
  //   coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop",
  //   pages: 688,
  //   publishedDate: "1965-08-01",
  //   format: "eBook",
  //   fileSize: "4.2 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 5,
  //   title: "The Silent Patient",
  //   author: "Alex Michaelides",
  //   category: "Thriller",
  //   price: 10.99,
  //   originalPrice: 14.99,
  //   rating: 4.4,
  //   reviews: 4567,
  //   description: "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
  //   coverImage: "https://images.unsplash.com/photo-1535666669445-e8c15cd2e7d9?w=400&h=600&fit=crop",
  //   pages: 336,
  //   publishedDate: "2019-02-05",
  //   format: "eBook",
  //   fileSize: "3.0 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 6,
  //   title: "The Love Hypothesis",
  //   author: "Ali Hazelwood",
  //   category: "Romance",
  //   price: 9.99,
  //   originalPrice: 12.99,
  //   rating: 4.3,
  //   reviews: 2345,
  //   description: "As a third-year Ph.D. candidate, Olive Smith doesn't believe in lasting romantic relationships--but her best friend does, and that's what got her into this situation. Convincing Anh that Olive is dating and well on her way to a happily ever after was always going to take more than hand-wavy Jedi mind tricks: Scientists require proof. So, like any self-respecting biologist, Olive panics and kisses the first man she sees.",
  //   coverImage: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400&h=600&fit=crop",
  //   pages: 384,
  //   publishedDate: "2021-09-14",
  //   format: "eBook",
  //   fileSize: "2.9 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 7,
  //   title: "Steve Jobs",
  //   author: "Walter Isaacson",
  //   category: "Biography",
  //   price: 15.99,
  //   originalPrice: 21.99,
  //   rating: 4.6,
  //   reviews: 6789,
  //   description: "Based on more than forty interviews with Steve Jobs conducted over two years--as well as interviews with more than 100 family members, friends, adversaries, competitors, and colleagues--Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries.",
  //   coverImage: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=400&h=600&fit=crop",
  //   pages: 656,
  //   publishedDate: "2011-10-24",
  //   format: "eBook",
  //   fileSize: "4.5 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 8,
  //   title: "Think Like a Monk",
  //   author: "Jay Shetty",
  //   category: "Self-Help",
  //   price: 13.99,
  //   originalPrice: 17.99,
  //   rating: 4.5,
  //   reviews: 3456,
  //   description: "Jay Shetty, social media superstar and host of the #1 podcast On Purpose, distills the timeless wisdom he learned as a monk into practical steps anyone can take every day to live a less anxious, more meaningful life. When you think like a monk, you'll understand: How to overcome negativity, How to stop overthinking, Why comparison kills love.",
  //   coverImage: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=400&h=600&fit=crop",
  //   pages: 352,
  //   publishedDate: "2020-09-08",
  //   format: "eBook",
  //   fileSize: "3.2 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 9,
  //   title: "The 7 Habits of Highly Effective People",
  //   author: "Stephen R. Covey",
  //   category: "Business",
  //   price: 11.99,
  //   originalPrice: 15.99,
  //   rating: 4.7,
  //   reviews: 9876,
  //   description: "One of the most inspiring and impactful books ever written, The 7 Habits of Highly Effective People has captivated readers for nearly three decades. It has transformed the lives of presidents and CEOs, educators and parents--millions of people of all ages and occupations. Now, this 30th anniversary edition of the timeless classic commemorates the wisdom of the 7 habits.",
  //   coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop",
  //   pages: 464,
  //   publishedDate: "1989-08-15",
  //   format: "eBook",
  //   fileSize: "3.5 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 10,
  //   title: "Project Hail Mary",
  //   author: "Andy Weir",
  //   category: "Sci-Fi",
  //   price: 12.99,
  //   originalPrice: 16.99,
  //   rating: 4.8,
  //   reviews: 5432,
  //   description: "Ryland Grace is the sole survivor on a desperate, last-chance mission--and if he fails, humanity and the earth itself will perish. Except that right now, he doesn't know that. He can't even remember his own name, let alone the nature of his assignment or how to complete it. All he knows is that he's been asleep for a very, very long time. And he's just been awakened to find himself millions of miles from home, with nothing but two corpses for company.",
  //   coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=600&fit=crop",
  //   pages: 496,
  //   publishedDate: "2021-05-04",
  //   format: "eBook",
  //   fileSize: "3.8 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 11,
  //   title: "Gone Girl",
  //   author: "Gillian Flynn",
  //   category: "Thriller",
  //   price: 10.99,
  //   originalPrice: 13.99,
  //   rating: 4.5,
  //   reviews: 7654,
  //   description: "On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne's fifth wedding anniversary. Presents are being wrapped and reservations are being made when Nick's clever and beautiful wife disappears. Husband-of-the-Year Nick isn't doing himself any favors with cringe-worthy daydreams about the slope and shape of his wife's head, but passages from Amy's diary reveal the alpha-girl perfectionist could have put anyone dangerously on edge.",
  //   coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop",
  //   pages: 432,
  //   publishedDate: "2012-06-05",
  //   format: "eBook",
  //   fileSize: "3.3 MB",
  //   priceId: "price_1QQk5bCLF4yRKjWwdBwJEfJO"
  // },
  // {
  //   id: 12,
  //   title: "It Ends with Us",
  //   author: "Colleen Hoover",
  //   category: "Romance",
  //   price: 9.99,
  //   originalPrice: 12.99,
  //   rating: 4.6,
  //   reviews: 8901,
  //   description: "Lily hasn't always had it easy, but that's never stopped her from working hard for the life she wants. She's come a long way from the small town where she grew up--she graduated from college, moved to Boston, and started her own business. And when she feels a spark with a gorgeous neurosurgeon named Ryle Kincaid, everything in Lily's life seems too good to be true.",
  //   coverImage: "https://images.unsplash.com/photo-1529070538774-1843cb3265df?w=400&h=600&fit=crop",
  //   pages: 384,
  //   publishedDate: "2016-08-02",
  //   format: "eBook",
  //   fileSize: "2.7 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 13,
  //   title: "Educated",
  //   author: "Tara Westover",
  //   category: "Biography",
  //   price: 14.99,
  //   originalPrice: 18.99,
  //   rating: 4.7,
  //   reviews: 6543,
  //   description: "Tara Westover was seventeen the first time she set foot in a classroom. Born to survivalists in the mountains of Idaho, she prepared for the end of the world by stockpiling home-canned peaches and sleeping with her 'head-for-the-hills bag'. In the summer she stewed herbs for her mother, a midwife and healer, and in the winter she salvaged in her father's junkyard.",
  //   coverImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop",
  //   pages: 352,
  //   publishedDate: "2018-02-20",
  //   format: "eBook",
  //   fileSize: "3.1 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 14,
  //   title: "Where the Crawdads Sing",
  //   author: "Delia Owens",
  //   category: "Fiction",
  //   price: 11.99,
  //   originalPrice: 15.99,
  //   rating: 4.8,
  //   reviews: 9012,
  //   description: "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl. But Kya is not what they say. Sensitive and intelligent, she has survived for years alone in the marsh that she calls home.",
  //   coverImage: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=400&h=600&fit=crop",
  //   pages: 384,
  //   publishedDate: "2018-08-14",
  //   format: "eBook",
  //   fileSize: "3.0 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 15,
  //   title: "Sapiens: A Brief History of Humankind",
  //   author: "Yuval Noah Harari",
  //   category: "Business",
  //   price: 16.99,
  //   originalPrice: 22.99,
  //   rating: 4.6,
  //   reviews: 7890,
  //   description: "From a renowned historian comes a groundbreaking narrative of humanity's creation and evolution--a #1 international bestseller--that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be 'human.' One hundred thousand years ago, at least six different species of humans inhabited Earth. Yet today there is only one--homo sapiens. What happened to the others?",
  //   coverImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=600&fit=crop",
  //   pages: 464,
  //   publishedDate: "2011-01-01",
  //   format: "eBook",
  //   fileSize: "4.1 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 16,
  //   title: "The Subtle Art of Not Giving a F*ck",
  //   author: "Mark Manson",
  //   category: "Self-Help",
  //   price: 10.99,
  //   originalPrice: 14.99,
  //   rating: 4.4,
  //   reviews: 8765,
  //   description: "In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be 'positive' all the time so that we can truly become better, happier people. For decades, we've been told that positive thinking is the key to a happy, rich life. But those days are over. Stop trying to be positive all the time. It's exhausting.",
  //   coverImage: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=600&fit=crop",
  //   pages: 224,
  //   publishedDate: "2016-09-13",
  //   format: "eBook",
  //   fileSize: "2.4 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 17,
  //   title: "The Hunger Games",
  //   author: "Suzanne Collins",
  //   category: "Fiction",
  //   price: 9.99,
  //   originalPrice: 13.99,
  //   rating: 4.7,
  //   reviews: 10234,
  //   description: "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.",
  //   coverImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop",
  //   pages: 374,
  //   publishedDate: "2008-09-14",
  //   format: "eBook",
  //   fileSize: "2.9 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 18,
  //   title: "The Martian",
  //   author: "Andy Weir",
  //   category: "Sci-Fi",
  //   price: 11.99,
  //   originalPrice: 15.99,
  //   rating: 4.8,
  //   reviews: 9876,
  //   description: "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there. After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he's alive.",
  //   coverImage: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=600&fit=crop",
  //   pages: 369,
  //   publishedDate: "2011-09-27",
  //   format: "eBook",
  //   fileSize: "2.8 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 19,
  //   title: "The Girl on the Train",
  //   author: "Paula Hawkins",
  //   category: "Thriller",
  //   price: 10.99,
  //   originalPrice: 14.99,
  //   rating: 4.3,
  //   reviews: 6543,
  //   description: "Rachel takes the same commuter train every morning and night. Every day she rattles down the track, flashes past a stretch of cozy suburban homes, and stops at the signal that allows her to daily watch the same couple breakfasting on their deck. She's even started to feel like she knows them. Jess and Jason, she calls them. Their life--as she sees it--is perfect. Not unlike the life she recently lost.",
  //   coverImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=600&fit=crop",
  //   pages: 336,
  //   publishedDate: "2015-01-13",
  //   format: "eBook",
  //   fileSize: "2.6 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // },
  // {
  //   id: 20,
  //   title: "Pride and Prejudice",
  //   author: "Jane Austen",
  //   category: "Romance",
  //   price: 7.99,
  //   originalPrice: 9.99,
  //   rating: 4.9,
  //   reviews: 12345,
  //   description: "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work 'her own darling child' and its vivacious heroine, Elizabeth Bennet, 'as delightful a creature as ever appeared in print.'",
  //   coverImage: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=600&fit=crop",
  //   pages: 279,
  //   publishedDate: "1813-01-28",
  //   format: "eBook",
  //   fileSize: "2.2 MB",
  //   priceId: "price_1SXi6UA5bB22UqX8GG0OvkZB"
  // }
];

// Export for use in other files
export { books };
